global:
  scrape_interval: 30s
  scrape_timeout: 5s
  evaluation_interval: 30s

scrape_configs:
  - job_name: nutrico-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:8080
